basedir: /

# html lang
language: "en"

# main menu navigation
menu:
  # welcome/cfp.html: call for papers
  welcome: welcome
  talks_speakers: talks
  # schedule: schedule
  sponsor: sponsor
  # scommentare per generare pagina
  # menu item for workshop
  workshop: workshop

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
   generative-AI-LLMs-PHP: Introduction to Generative AI and LLMs in PHP


# welcome submenu
welcome_submenu:
  about: about
  coc: code of conduct
  safety: health and safety
  scholarships: scholarships
  where: where
  # delete this row to take out of the menu
  # cfp: call for papers

# stylesheets loaded in the <head>
stylesheets:
  - /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
  - /assets/js/menu.js
